#include <atomic>
#include "ctagSoundProcessor.hpp"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorbbeats : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            ctagSoundProcessorbbeats();
            virtual ~ctagSoundProcessorbbeats();

        private:
            int process_param( const ProcessData &data, int cv_myparm, int my_parm, int parm_range ); // rescale incoming data
            float process_param_float( const ProcessData &data, int cv_myparm, int my_parm ); // rescale incoming data to 0.0-1.0
            virtual void knowYourself() override;

            // private attributes could go here
            float beat_val_A = 0.0;      // Currently calculated or temporarily stored audio value for ByteBeatA
            float beat_val_B = 0.0;      // Currently calculated or temporarily stored audio value for ByteBeatB
            uint32_t t1 = 0;             // Iterator for ByteBeat1
            uint32_t t2 = 0;             // Iterator for ByteBeat2
            uint16_t slow_down_A = 0;    // Speed counter for ByteBeat1
            int slow_down_A_factor = 0;  // Speed factor for ByteBeat1
            uint16_t slow_down_B = 0;    // Speed counter for ByteBeat2
            int slow_down_B_factor = 0;  // Speed factor for ByteBeat2

            int beat_index_A = 0;         // Used to decide which ByteBeat1 from the lists below has been selected by controller / CV
            int beat_index_B = 0;         // Used to decide which ByteBeat2 from the lists below has been selected by controller / CV
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> beatA_stop, trig_beatA_stop;
            atomic<int32_t> beatA_reset_on_stop, trig_beatA_reset_on_stop;
            atomic<int32_t> beatB_stop, trig_beatB_stop;
            atomic<int32_t> beatB_reset_on_stop, trig_beatB_reset_on_stop;
            atomic<int32_t> beatA_backwards, trig_beatA_backwards;
            atomic<int32_t> beatB_backwards, trig_beatB_backwards;
            atomic<int32_t> beatA_select, cv_beatA_select;
            atomic<int32_t> beatB_select, cv_beatB_select;
            atomic<int32_t> beatA_pitch, cv_beatA_pitch;
            atomic<int32_t> beatB_pitch, cv_beatB_pitch;
            atomic<int32_t> xFadeA_B, cv_xFadeA_B;
	// sectionHpp
        };
    }
}