#include <atomic>
#include "ctagSoundProcessor.hpp"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorbbeats : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            ctagSoundProcessorbbeats();
            virtual ~ctagSoundProcessorbbeats();

        private:
            virtual void knowYourself() override;

            // private attributes could go here
            float beat_val = 0.0;        // Currently calculated or temporarily stored audio value for output-buffer
            uint32_t t1 = 0;             // Iterator for ByteBeat1
            uint32_t t2 = 0;             // Iterator for ByteBeat2
            uint32_t slow_down_A = 0;    // Speed counter for ByteBeat1
            int slow_down_A_factor = 0;  // Speed factor for ByteBeat1

            int beat_index_A = 0;         // Used to decide which ByteBeat from the lists below has been selected by controller / CV
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> beatA_stop, trig_beatA_stop;
            atomic<int32_t> beatA_reset_on_stop, trig_beatA_reset_on_stop;
            atomic<int32_t> beatB_stop, trig_beatB_stop;
            atomic<int32_t> beatB_reset_on_stop, trig_beatB_reset_on_stop;
            atomic<int32_t> beatA_backwards, trig_beatA_backwards;
            atomic<int32_t> beatB_backwards, trig_beatB_backwards;
            atomic<int32_t> beatA_select, cv_beatA_select;
            atomic<int32_t> beatB_select, cv_beatB_select;
            atomic<int32_t> beatA_pitch, cv_beatA_pitch;
            atomic<int32_t> beatB_pitch, cv_beatB_pitch;
            atomic<int32_t> xFadeA_B, cv_xFadeA_B;
	// sectionHpp
        };
    }
}